"""
Agent 1 Factory Definition.
"""

import os
from typing import Dict, Any, Optional
from .prompt import AGENT_NAME, AGENT_ROLE, SYSTEM_INSTRUCTION
from .tools import TOOLS_LIST

try:
    from google import genai
    from google.genai import types
    GENAI_AVAILABLE = True
except ImportError:
    GENAI_AVAILABLE = False


class Agent1:
    """Agent 1 Implementation Template."""

    def __init__(
        self,
        model_name: str = "gemini-2.5-flash",
        temperature: float = 0.2,
        api_key: Optional[str] = None
    ):
        self.id = "agent1"
        self.name = AGENT_NAME
        self.role = AGENT_ROLE
        self.model_name = model_name
        self.temperature = temperature
        self.api_key = api_key or os.environ.get("GOOGLE_API_KEY")
        self.client = genai.Client(api_key=self.api_key) if (self.api_key and GENAI_AVAILABLE) else None
        self.tools = TOOLS_LIST

    def run(self, prompt: str, context: Optional[Dict[str, Any]] = None) -> Dict[str, Any]:
        """Execute agent processing on prompt."""
        if not self.client:
            return {
                "agent_id": self.id,
                "agent_name": self.name,
                "role": self.role,
                "response": f"[{self.name}] Processed query: '{prompt}'. Output generated by template orchestrator.",
                "status": "success"
            }

        try:
            config = types.GenerateContentConfig(
                system_instruction=SYSTEM_INSTRUCTION,
                temperature=self.temperature
            )
            response = self.client.models.generate_content(
                model=self.model_name,
                contents=prompt,
                config=config
            )
            return {
                "agent_id": self.id,
                "agent_name": self.name,
                "role": self.role,
                "response": response.text,
                "status": "success"
            }
        except Exception as e:
            return {
                "agent_id": self.id,
                "agent_name": self.name,
                "role": self.role,
                "error": str(e),
                "response": f"Error running {self.name}: {str(e)}",
                "status": "error"
            }


def get_agent(**kwargs) -> Agent1:
    return Agent1(**kwargs)